server:
  port: 8024
spring:
    datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:log4jdbc:mysql://127.0.0.1:3308/insta?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
      username: cyast
      password: cya1234
mybatis:
  type-aliases-package: com.cya.untact.dto
custom:
  logging:
    dir: log
    level: debug