server:
  port: 8024
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:log4jdbc:mysql://127.0.0.1:3308/insta?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
      username: cyast
      password: cya1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: duddk1551@gmail.com
    password: jftmofrkhuuqbbxw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  type-aliases-package: com.cya.untact.dto
custom:
  needToChangePasswordFreeDays: 90
  siteMainUri: "http://localhost:8024/"
  siteName: "IVORY"
  emailFrom: no-reply@localhost
  emailFromName: IVORY NOTICE ROBOT
  logging:
    dir: log
    level: debug